{
 "title": "ImageSvc - PromEx Broadway Dashboard",
 "description": "All the data that is presented here is captured by the PromEx Broadway plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/broadway.ex)",
 "tags": [
  "PromEx",
  "Broadway",
  "image_svc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(image_svc_prom_ex_prom_ex_status_info, job)"
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": "label_values(image_svc_prom_ex_prom_ex_status_info{job=\"$job\"}, instance)"
   },
   {
    "name": "broadway_module",
    "label": "Broadway Module",
    "query": "label_values(image_svc_prom_ex_broadway_init_status_info, name)"
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broadway Module",
   "type": "stat",
   "description": "The Broadway module currently selected for viewing metrics.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_broadway_init_status_info{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}"
    }
   ]
  },
  {
   "title": "Message Processors",
   "type": "table",
   "description": "The settings that were set for the selected Broadway module.",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_broadway_init_processor_concurrency_value|image_svc_prom_ex_broadway_init_processor_max_demand_value|image_svc_prom_ex_broadway_init_processor_hibernate_after_milliseconds\", job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}"
    }
   ]
  },
  {
   "title": "Batch Processors",
   "type": "table",
   "description": "The settings that were set for the selected Broadway module.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_broadway_init_batcher_batch_timeout_milliseconds|image_svc_prom_ex_broadway_init_batcher_batch_size_value|image_svc_prom_ex_broadway_init_batcher_concurrency_value|image_svc_prom_ex_broadway_init_batcher_hibernate_after_milliseconds\", job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}"
    }
   ]
  },
  {
   "title": "Default Module Settings",
   "type": "table",
   "description": "The settings that were set for the selected Broadway module.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_broadway_init_shutdown_default_milliseconds|image_svc_prom_ex_broadway_init_max_restarts_default_value|image_svc_prom_ex_broadway_init_max_duration_default_milliseconds|image_svc_prom_ex_broadway_init_resubscribe_interval_default_milliseconds|image_svc_prom_ex_broadway_init_hibernate_after_default_milliseconds\", job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}"
    }
   ]
  },
  {
   "title": "Message Success Percentage (Last 24h)",
   "type": "stat",
   "description": "A percentage of Broadway messages that did not result in errors over the past 24 hours.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[24h])) / sum(increase({__name__=~\"image_svc_prom_ex_broadway_process_message_duration_milliseconds_count|image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_count\", job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[24h])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Messages processed (Last 24h)",
   "type": "stat",
   "description": "The number of messages processed in the last 24 hours.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[24h]))"
    }
   ]
  },
  {
   "title": "Batches processed (Last 24h)",
   "type": "stat",
   "description": "The number of messages processed in the last 24 hours.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[24h]))"
    }
   ]
  },
  {
   "title": "Message Success Percentage (Last 1h)",
   "type": "stat",
   "description": "A percentage of Broadway messages that did not result in errors over the past hour.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[1h])) / sum(increase({__name__=~\"image_svc_prom_ex_broadway_process_message_duration_milliseconds_count|image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_count\", job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[1h])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Messages processed (Last 1h)",
   "type": "stat",
   "description": "The number of messages processed in the last hour.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[1h]))"
    }
   ]
  },
  {
   "title": "Batches processed (Last 1h)",
   "type": "stat",
   "description": "The number of messages processed in the last hour.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[1h]))"
    }
   ]
  },
  { "title": "Message Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Message Processing Time",
   "type": "heatmap",
   "description": "A heatmap showing the processing time across all of the messages (regardless of processor key).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_message_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Message Exception Time",
   "type": "heatmap",
   "description": "A heatmap showing the processing time across all of the messages that resulted in an exception (regardless of processor key).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Message Processing Time",
   "type": "graph",
   "description": "The average processing time per processor key.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_message_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(processor_key) / sum(irate(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(processor_key)",
     "legendFormat": "{{ processor_key }}"
    }
   ]
  },
  {
   "title": "Average Message Exception Time",
   "type": "graph",
   "description": "The average processing time per processor key that resulted in an exception.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(processor_key, reason) / sum(irate(image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(processor_key, reason)",
     "legendFormat": "{{ processor_key }} :: {{ reason }}"
    }
   ]
  },
  {
   "title": "Messages Processed",
   "type": "graph",
   "description": "Shows the number of messages that we processed per processor key.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "locale", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "irate(image_svc_prom_ex_broadway_process_message_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])",
     "legendFormat": "{{ processor_key }}"
    }
   ]
  },
  {
   "title": "Message Exceptions",
   "type": "graph",
   "description": "Shows the number of messages that we processed per processor key that resulted in exceptions.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "locale", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "irate(image_svc_prom_ex_broadway_process_message_exception_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])",
     "legendFormat": "{{ processor_key }} :: {{ reason }}"
    }
   ]
  },
  { "title": "Batch Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Batch Processing Time",
   "type": "heatmap",
   "description": "A heatmap showing the processing time across all of the batches (regardless of batcher key).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Successful Messages per Batch",
   "type": "graph",
   "description": "The average number of messages in a batch that were successful",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "locale", "label": "Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_batch_success_size_sum{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher) / sum(irate(image_svc_prom_ex_broadway_process_batch_success_size_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher)",
     "legendFormat": "{{ batcher }}"
    }
   ]
  },
  {
   "title": "Average Batch Processing Time",
   "type": "graph",
   "description": "The average processing time per batcher key.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms", "label": "Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher) / sum(irate(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher)",
     "legendFormat": "{{ batcher }}"
    }
   ]
  },
  {
   "title": "Average Failed Messages per Batch",
   "type": "graph",
   "description": "The average number of messages in a batch that failed to process",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "locale", "label": "Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(image_svc_prom_ex_broadway_process_batch_failure_size_sum{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher) / sum(irate(image_svc_prom_ex_broadway_process_batch_failure_size_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])) by(batcher)",
     "legendFormat": "{{ batcher }}"
    }
   ]
  },
  {
   "title": "Batches Processed",
   "type": "graph",
   "description": "Shows the number of batches that we processed per batch key.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "locale", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "irate(image_svc_prom_ex_broadway_process_batch_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", name=\"$broadway_module\"}[$interval])",
     "legendFormat": "{{ batcher }}"
    }
   ]
  }
 ]
}